Hummingbird-Team-Project/hummingbird-app

ios/Podfile.lock, lib/core/const/box_keys.dart, lib/core/router/router.dart, lib/core/utils/delay.dart, lib/main.dart, lib/src/models/env.dart, lib/src/models/token_model.dart, lib/src/providers/auth/google_login_provider.dart, lib/src/repositories/auth/google_login_api.dart, lib/src/views/login/google_login_button.dart, lib/src/views/login/login_screen.dart, lib/src/views/more/view/more_screen.dart, lib/src/views/splash/app_initialize.dart, lib/src/views/splash/splash_screen.dart, pubspec.lock, pubspec.yaml
앱 초기화를 위한 splash screen 구현
- 인증 기능 정상 작동을 위한 앱 초기화 로직 추가
- flutter_secure_storage 및 path_provider 패키지 추가
- 로그인 페이지 내 mxnContainer 레이아웃 적용
- 앱 초기화 로직 및 위치에 대한 리뷰 필요
- pubspec.yaml / pubspec.lock / ios/Podfile.lock 파일 변경
- Flutter Secure Storage 안드로이드 작동 여부 및 추가 설정 필요사항은 성현님이 확인해주시길 요청 드림
=> feat(screen): add splash screen for app initializing

lib/src/datasource/local/study_record/study_record_local_datasource.dart, lib/src/views/home/widgets/subject/subject_list_widget.dart
유저 학습 데이터 테스트코드 및 Log 삭제
- 주요 변경 사항 1
- 주요 변경 사항 2
- 주요 변경 사항 3
=> 유저 학습 데이터 테스트코드 및 Log 삭제

lib/core/router/router.dart, lib/core/utils/show_confirm_dialog.dart, lib/core/utils/show_snack_bar.dart, lib/main.dart, lib/src/app_initialize.dart, lib/src/providers/auth/auth_provider.dart, lib/src/providers/auth/google_login_provider.dart, lib/src/views/login/google_login_button.dart, lib/src/views/more/view/more_screen.dart, lib/src/views/splash/splash_screen.dart
인증 관련 기능 동작을 위한 라우터 수정 및 스낵바, 컨펌 다이얼로그 추가
- 인증 상태에 따른 라우터 리다이렉트 적용
- 유저 피드백 전달을 위한 스낵바 추가
- 유저 컨펌 여부 로직 반영을 위한 컨펌 다이얼로그 추가
=> feat(route): add global navigator key and auth functionality

lib/src/datasource/local/study_record/study_record_local_datasource.dart, lib/src/providers/suduck_timer/suduck_timer_provider.dart, lib/src/repositories/study_record/study_record_repository.dart, lib/src/viewmodels/study_record/study_record_viewmodel.dart, lib/src/views/home/widgets/subject/subject_list_widget.dart, lib/src/views/home/widgets/timer/suduck_timer_widget.dart, lib/src/views/splash/app_initialize.dart
- 주요 변경 사항 1
- 주요 변경 사항 2
- 주요 변경 사항 3
=> Feat타이머 레이아웃 및 모달 타이머 구현

lib/src/providers/suduck_timer/suduck_timer_provider.dart, lib/src/views/home/widgets/subject/subject_list_widget.dart, lib/src/views/home/widgets/timer/suduck_timer_widget.dart
SubjectListwidet 의 ListTile 기능 추가 및 수정 TimerWidget 색상 변경 로직 추가
Feat: add subject selection and timer functionality in SubjectListWidget
=> SubjectListwidet 의 ListTile 기능 추가 및 수정 TimerWidget 색상 변경 로직 추가

lib/src/datasource/local/study_record/study_record_local_datasource.dart, lib/src/repositories/study_record/study_record_repository.dart
Feat: add method to retrieve study records by date
기존입력값과 동일한 String date를 입력받아 studyRecord를 불러오는 로직 추가
=> Feat: add method to retrieve study records by date

lib/core/router/bottom_nav_bar.dart, lib/core/router/router.dart, lib/core/utils/get_formatted_time.dart, lib/src/providers/suduck_timer/suduck_timer_provider.dart, lib/src/viewmodels/timer/timer_bg_color_provider.dart, lib/src/views/home/widgets/subject/subject_list_widget.dart, lib/src/views/home/widgets/timer/suduck_timer_modal_widget.dart, lib/src/views/home/widgets/timer/suduck_timer_widget.dart, lib/src/views/more/views/more_screen.dart, lib/src/views/more/widgets/logout_btn_widget.dart, lib/src/views/more/widgets/user_auth_widget.dart
타이머 모달 추가 및 로그아웃 레이아웃 추가
Feat: add method to retrieve study records by date
Feat: implement Suduck timer modal and refactor timer logic
Feat: refactor authentication UI and add logout button component
=> 타이머 모달 추가 및 로그아웃 레이아웃 추가

lib/main.dart
=> feat: set application to portrait mode on startup

android/app/src/main/AndroidManifest.xml, ios/Podfile.lock, lib/src/views/more/widgets/modules/send_email.dart, pubspec.lock, pubspec.yaml
=> feat: add send email feature

ios/Podfile.lock, lib/src/providers/suduck_timer/suduck_timer_provider.dart, lib/src/viewmodels/timer/timer_bg_color_provider.dart, lib/src/views/home/widgets/timer/suduck_timer_widget.dart
Feat unassign subjects
[- 주요 변경 사항 1](feat: add reset functionality to SuDuckTimer and improve timer widget layout)
[- 주요 변경 사항 2](feat: update timer background color handling)
[- 주요 변경 사항 3](refactor: improve timer variable naming and encapsulate timer cancellation logic)
=> 과목 할당 해제 기능 추가 및 색상 애니메이션 수정 

lib/src/views/splash/splash_screen.dart
=> Fix : where setstate was called even after dispose by additionally managing the timer controller.

lib/core/const/box_keys.dart, lib/core/const/study_group.dart, lib/core/router/router.dart, lib/src/app_initialize.dart, lib/src/datasource/local/app_setting/app_setting_local_datasource.dart, lib/src/datasource/local/user_setting/user_setting_local_datasource.dart, lib/src/datasource/remote/auth/google_login_api.dart, lib/src/datasource/remote/user/get_profile_api.dart, lib/src/datasource/remote/user/update_profile_api.dart, lib/src/datasource/remote/user/user_setting_remote_datasource.dart, lib/src/models/setting/app_setting.dart, lib/src/models/setting/user_setting.dart, lib/src/providers/auth/google_login_provider.dart, lib/src/repositories/app_setting/app_setting_repository.dart, lib/src/repositories/user_setting/user_setting_repository.dart, lib/src/viewmodels/app_setting/app_setting_view_model.dart, lib/src/viewmodels/study_record/study_record_viewmodel.dart, lib/src/viewmodels/user_setting/user_setting_view_model.dart, lib/src/views/more/views/settings_screen/select_group_screen.dart, lib/src/views/tutorial/profile_setting_screen.dart, lib/src/views/tutorial/study_setting_screen.dart, lib/src/views/tutorial/widgets/page_transition_button_widget.dart, lib/src/views/tutorial/widgets/select_group_bottom_sheet.dart
…torial screen
- 유저 프로필 기능 구현
- 튜토리얼 화면 구현 
- 라우터에 앱을 설치했을 시 튜토리얼 화면으로 이동하도록 수정
- 유저 세팅에 유저 아이디 속성 추가
- login() 메서드에 유저 아이디 유저 세팅에 추가하는 로직 추가
=> 유저 프로필 기능 구현 및 튜토리얼 화면 구현

lib/core/router/router.dart, lib/src/datasource/remote/subject_record/subject_remote_datasource.dart, lib/src/repositories/d_day/d_day_repository.dart, lib/src/repositories/subject/subject_repository.dart, lib/src/repositories/user_setting/user_setting_repository.dart, lib/src/viewmodels/d_day/d_day_view_model.dart, lib/src/viewmodels/user_setting/user_setting_view_model.dart, lib/src/views/home/widgets/d_day_widget/d_day_list_tile_widget.dart, lib/src/views/more/views/more_screen.dart, lib/src/views/more/views/profile_screen/profile_screen.dart, lib/src/views/more/widgets/profile_and_btn_widget.dart, lib/src/views/more/widgets/safe_btn_widget.dart, lib/src/views/more/widgets/user_profile_widget.dart, lib/src/views/tutorial/profile_setting_screen.dart, lib/src/views/tutorial/widgets/profile_container_widget.dart
- more 화면에 유저 프로필 추가
- 유저 세팅 remote datasource 구현 완료
- D-day , user setting 프로바이더 keepAlive true 로 변경
=> Feat: User profile layout and user setting remote datasource

lib/src/repositories/d_day/d_day_repository.dart, lib/src/viewmodels/d_day/d_day_view_model.dart, lib/src/viewmodels/user_setting/user_setting_view_model.dart, lib/src/views/more/views/profile_screen/profile_screen.dart, lib/src/views/more/widgets/profile_and_btn_widget.dart, lib/src/views/tutorial/profile_setting_screen.dart, lib/src/views/tutorial/study_setting_screen.dart, lib/src/views/tutorial/widgets/profile_container_widget.dart
- 프로필 설정 화면 오버플로우 문제 해결
- d-day 리포지토리 getAllDDay() 메서드 내에 있던 버그 수정
=> Fix: fix layout overflow in profile screen and d-day repository

lib/src/datasource/remote/subject_record/get_study_record_by_date_api.dart, lib/src/repositories/study_record/study_record_repository.dart
공부 기록 응답에 컬러와 순서 추가
- 검은색으로 색상이 표시되던 버그 픽스
=> fix: update get study record response dto

lib/src/views/more/widgets/app_chor/privacy_policy_widget.dart
개인정보 처리방침 url수정
- 주요 변경 사항 1
- 주요 변경 사항 2
- 주요 변경 사항 3
=> Fix: update privacy policy URL in PrivacyPolicyWidget

lib/src/providers/dio_providers/dio_interceptor.dart
=> fix: update refresh token logic

lib/core/utils/get_epoch_time.dart, lib/src/providers/suduck_timer/suduck_timer_provider.dart, lib/src/providers/suduck_timer/suduck_timer_provider_2_0.dart, lib/src/repositories/study_record/study_record_repository.dart, lib/src/repositories/subject/subject_repository.dart, lib/src/views/home/suduck_timer_focus_mode_screen.dart, lib/src/views/home/widgets/subject/subject_list_widget.dart, lib/src/views/home/widgets/timer/suduck_timer_controll_bar_widget.dart, lib/src/views/home/widgets/timer/suduck_timer_widget.dart
Refactor : SuduckTimer 수정 및 SubjectRepo 수정
SuduckTimerProvider2.0으로 수정
_restore에 관한 내용삭제및 로직 수정
SubjectRepo의 Get 수정
=> Refactor : SuduckTimer 수정 및 SubjectRepo 수정

lib/core/utils/format_date.dart, lib/src/datasource/remote/subject_record/get_study_records_by_range_api.dart, lib/src/repositories/study_record/study_record_repository.dart, lib/src/viewmodels/study_record/study_record_viewmodel.dart
통계화면에서 네트워크 상태에 따라 데이터 소스 반영하도록 수정
=> feat(statistics): add get study record by range repository method

lib/src/repositories/study_record/study_record_repository.dart, lib/src/viewmodels/study_record/study_record_viewmodel.dart, lib/src/views/home/widgets/subject/subject_list_widget.dart
Refactor: update addStudyRecord method to include total duration calculation
- TotalDuration add시 추가
- StartAt , EndAt SuduckTimerProvider에서 받아오게 변경 
EndAt에 기존에 ~/ 1000; <- 이게 있었는데 변경된 로직은 getter에서 미리 1000을 나눠서 보내줍니다. 
로직상 문제가 없어보이나 한번 서버쪽에도 확인 부탁드려요
=> Refactor: update addStudyRecord method to include total duration calculation

lib/src/viewmodels/study_record/study_record_viewmodel.dart
- StudyRecordViewModel 에 있는 loadStudyRecordsByPeriod() 메서드 서버에 여러번 호출하던 버그 수정
=> Fix: Optimize study record retrieval in StudyRecordViewModel

lib/src/providers/suduck_timer/suduck_timer_provider_2_0.dart
타이머 네트워크 미연결시 동작안하게 변경
타이머 네트워크 미연결시 동작안하게 변경
=> Feat: Add network connectivity check before starting timer

lib/src/views/more/widgets/user_profile/user_profile_widget.dart
=> Feat: Improve user profile display by formatting nickname with label

lib/src/providers/dio_providers/dio_interceptor.dart, lib/src/providers/dio_providers/refresh_token_dio_client_provider.dart
디버그용으로 추가한 에러 메시지 스낵바 메시지 수정
- 리프레시 토큰 요청 실패 시 로그아웃 되도록 처리
- dio interceptor 에러 메시지 수정
=> fix: update error message snackbar for production

lib/src/repositories/d_day/d_day_repository.dart, lib/src/repositories/study_record/study_record_repository.dart, lib/src/viewmodels/study_record/study_record_viewmodel.dart, lib/src/viewmodels/subject/subject_viewmodel.dart, pubspec.lock, pubspec.yaml
DDay, Subject, StudyRecord 리포지토리와 view model 에 남아있는 버그 수정
- DDayRepository 에 Hive 용 임시방편으로 dDayId에 Uuid 사용
- SubjectViewModel 에 있는userId, isConnected 관련 코드 제거
- StudyRecordViewModel 에 있는 userId, isConnected 관련 코드 제거
=> Fix: Remaining remote-related bugs in DDay, Subject, and StudyRecord

pubspec.yaml
pubspec.yaml 수정
- 주요 변경 사항 1
- 주요 변경 사항 2
- 주요 변경 사항 3
=> chore: remove unused dependencies from pubspec.yaml

lib/core/widgets/admob_widget.dart, lib/core/widgets/color_picker_widget.dart, lib/src/datasource/remote/d_day/d_day_remote_datasource.dart, lib/src/providers/review/review_provider.dart, lib/src/viewmodels/image_controller.dart, lib/src/viewmodels/study_record/study_record_viewmodel.dart, lib/src/views/home/widgets/timer/suduck_timer_widget.dart, lib/src/views/more/widgets/profile/profile_info_widget.dart, lib/src/views/more/widgets/profile/safe_button_widget.dart
StudyRecordViewModel 의 데이터를 날짜별로 병합하는 메서드 로직 변경된 서버에 맞게 수정
- loadStudyRecordByPeriod() 메서드의 로직 수정
- loadStudyRecordByDate() 메서드의 로직 수정
- Fix All import 해서 import 순서가 제대로 안되어 있던 파일들 수정
=> Refactor: Modify study record merging method

ios/Podfile.lock, lib/core/widgets/admob_widget.dart, lib/src/views/more/settings_screen/settings_screen.dart
- ScreenUtil 적용
안드로이드에서 화면 크기를 가지고 오는 방식이 달라  IOS와 안드로이드를 분리하여 처리
=> 안드로이드에서 광고 배너 크기 수정

lib/src/datasource/remote/subject/subject_remote_datasource.dart, lib/src/models/study_record/study_record.dart, lib/src/providers/suduck_timer/suduck_timer_provider_2_0.dart
studyRecord 모델변경  dateKey 추가
Subjects의 dummy를 subject로 변경
- 주요 변경 사항 1
- 주요 변경 사항 2
- 주요 변경 사항 3
=> feat: update subject handling and add dateKey to StudyRecord model

lib/src/views/home/suduck_timer_focus_mode_screen.dart, pubspec.lock, pubspec.yaml
- 집중화면에서 화면이 꺼지지 않도록 구현
집중화면에서 빠져 나오면 dispose되어 다른 화면에는 영향을 미치지 않음
=> [feat] focus_mode 화면 꺼지지 않도록 WakelockPlus적용

lib/core/router/bottom_nav_bar.dart, lib/core/router/router.dart, lib/core/utils/fcm.dart, lib/main.dart
fcm 루핑 회수 3->1회로
BottomNavBar Social 부활
=> Refactor: Update BottomNavBar and routing for Social screen; adjust FCM token retrieval attempts

.firebaserc, firebase.json, functions/.gitignore, functions/index.js, functions/package-lock.json, functions/package.json, ios/Podfile.lock, pubspec.lock, pubspec.yaml
리더보드용 FireStore DB Function작성및 의존성추가
루트폴더 / Function 에 firestore에 관련 코드 추가
=> Feat : Add Firebase configuration and Cloud Functions setup; update dependencies

lib/src/app_initialize.dart, lib/src/datasource/remote/user_setting/user_setting_remote_datasource.dart, lib/src/datasource/remote/user_setting/user_setting_remote_datasourcedart, lib/src/models/setting/user_setting.dart, lib/src/repositories/user_setting/user_setting_repository.dart, lib/src/viewmodels/user_setting/user_setting_view_model.dart, lib/src/views/tutorial/widgets/profile/set_profile_widget.dart
UserSetting Firebase 연동한 remote datasource 구현
- 기존 UserSettingLocadatasource 제거
- UserSettingRemoteDatasource 구현
- UserSetting 데이터 모델 Hive 대신 일반 freezed 로 변경 및 mbti, profileImgUrl 속성 추가
=> feat(remote-datasource): add Firebase integration for UserSetting

dailyLeaderboardUpdate, firebase.json, functions/index.js
LeaderBoard 로직 수정 및 랭킹코드 반영 
- 주요 변경 사항 1
- 주요 변경 사항 2
- 주요 변경 사항 3
=> fix : Implement daily leaderboard update function and configure Firebase emulators

lib/src/app_initialize.dart, lib/src/datasource/suduck_timer_state.dart, lib/src/providers/suduck_timer/suduck_timer_provider_2_0.dart, lib/src/repositories/suduck_timer_repositories.dart
타이머를 복구하는 코드
기존의 타이머를 복구하는과정에서 subjectId를 서버에서 받아와서 그것도 저장시켜서 과목까지 같이 복구할수있게끔 변경
=> Feat : New_TimerRestored

ios/Podfile.lock, lib/src/viewmodels/user_setting/user_setting_view_model.dart, lib/src/views/home/suduck_timer_focus_mode_screen.dart
자동 집중모드 색상 변경시 appBar와 body의 랜더링 속도가 달라 이쁘지 않았던 현상 수정
UserSettingViewModel 코드 수정
- FocusModeWidget의 appbar 삭제 후 그만큼의 spacer로 변경 및 뒤로가기 버튼 추가 
- ImgCtrl 인스턴스화
=> Fix : ColorTween BugFix

lib/src/views/home/suduck_timer_focus_mode_screen.dart, lib/src/views/home/widgets/subject/subject_list_widget.dart
과목 리스트 위젯의 시간이 두줄로 나오는것 수정 
집중모드 뒤로가기버튼 크기 증가
- 주요 변경 사항 1
- 주요 변경 사항 2
- 주요 변경 사항 3
=> Fix : Adjust back icon size and wrap in container; limit text lines in subject list

lib/src/views/tutorial/widgets/profile/set_profile_widget.dart
튜토리얼 유저 프로필 업데이트 안되는 버그 수정
- 주요 변경 사항 1
- 주요 변경 사항 2
- 주요 변경 사항 3
=> Fix : Update user settings before navigating to study settings page
